### ISSUE TITLE
Segmentation fault:11

### ISSUE THREAD

**Issue by ljrpicasso** [macournoyer/tinyrb#5]
I was able to build tinyrb almost completely. Near the end, I got the lines listed below. After that, trying to run tinyrb results in a segmentation fault.  Any ideas would be appreciated.
# versions

$ cc -v
Apple clang version 4.0 (tags/Apple/clang-421.0.60) (based on LLVM 3.1svn)
Target: x86_64-apple-darwin11.4.0
Thread model: posix

os/x 10.7.4
# notes from the end of make

```
     cc vm/array.c
     cc vm/hash.c
     cc vm/class.c
    1                                                                                 
     cc vm/error.c
     cc vm/kernel.c
     cc vm/object.c
      vm/object.c: In function ‘TrObject_object_id’:
      vm/object.c:81: warning: cast from pointer to integer of different size
    = tinyrb

  A tiny subset of Ruby with a Lua'esc VM.

 cc vm/block.c
 cc vm/compiler.c  
  make peg/leg
  In file included from peg.c:48:
  ./peg.peg-c:666:3: warning: unused label 'l77' [-Wunused-label]
    l77:;   yypos= yypos0; yythunkpos= yythunkpos0;
    ^~~~
  ./peg.peg-c:64:24: warning: unused variable 'yytextmax' [-Wunused-variable]
  YY_VARIABLE(int      ) yytextmax= 0;
                   ^
  2 warnings generated.
    leg vm/grammar.leg
 cc vm/grammar.c
 cc vm/vm.c
  vm/vm.c: In function ‘TrVM_load’:
  vm/vm.c:371: warning: comparison between signed and unsigned
 cc vm/tr.c
   link tinyrb
```

**Comment by macournoyer** [comment]
Building w/ clang doesn't work. Use GCC.

On Thu, Aug 23, 2012 at 2:39 PM, L. John Ribar notifications@github.comwrote:

> I was able to build tinyrb almost completely. Near the end, I got the
> lines listed below. After that, trying to run tinyrb results in a
> segmentation fault. Any ideas would be appreciated.
> versions
> 
> $ cc -v
> Apple clang version 4.0 (tags/Apple/clang-421.0.60) (based on LLVM 3.1svn)
> Target: x86_64-apple-darwin11.4.0
> Thread model: posix
> 
> os/x 10.7.4
> notes from the end of make
> 
> ```
>  cc vm/array.c
>  cc vm/hash.c
>  cc vm/class.c
> 1
>  cc vm/error.c
>  cc vm/kernel.c
>  cc vm/object.c
>   vm/object.c: In function ‘TrObject_object_id’:
>   vm/object.c:81: warning: cast from pointer to integer of different size
> = tinyrb
> ```
> 
>   A tiny subset of Ruby with a Lua'esc VM.
> 
>  cc vm/block.c
>  cc vm/compiler.c
>   make peg/leg
>   In file included from peg.c:48:
>   ./peg.peg-c:666:3: warning: unused label 'l77' [-Wunused-label]
>     l77:;   yypos= yypos0; yythunkpos= yythunkpos0;
>     ^~~~
>   ./peg.peg-c:64:24: warning: unused variable 'yytextmax' [-Wunused-variable]
>   YY_VARIABLE(int      ) yytextmax= 0;
>                    ^
>   2 warnings generated.
>     leg vm/grammar.leg
>  cc vm/grammar.c
>  cc vm/vm.c
>   vm/vm.c: In function ‘TrVM_load’:
>   vm/vm.c:371: warning: comparison between signed and unsigned
>  cc vm/tr.c
>    link tinyrb
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/macournoyer/tinyrb/issues/5.

## 

M-A
http://macournoyer.com

**Comment by MarkVillacampa** [comment]
Ran into the same issue, fortunately this is an easy fix :)

Out of curiosity, what makes tinyrb not compile with clang? tinyrb itself? or some of its dependencies?

BTW thanks for building this, learning a LOT! And most def going to buy your compilers book :)

EDIT: It seems not to work with llvm-gcc either. Tweaking all Makefiles to point to a custom installation of gcc seemed like a chaos. Compiled on ubuntu in a VM, worked fine :)

**Comment by macournoyer** [comment]
Hey @MarkVillacampa,

Unfortunately Clang can't compile the GC lib used by tinyrb (Boehm GC). No idea why. Maybe that has been resolved since and updating the dep would fix...

Glad you're learning a lot with this :) That was the goal (for me at least...)
